#!/bin/bash

rm .vimrc .zshrc .eslintrc .tmux.conf
cp ~/.vimrc .
cp ~/.zshrc .
cp ~/.eslintrc .
cp ~/.tmux.conf .

git add -A
read -p "Commit message: " msg
git commit -m "$msg"
git push origin master

