#!/bin/bash

sudo add-apt-repository -y ppa:snwh/pulp
sudo apt update
sudo apt install -y unity-tweak-tool paper-icon-theme paper-gtk-theme paper-cursor-theme

gsettings set org.gnome.desktop.interface gtk-theme "Paper"
gsettings set org.gnome.desktop.interface icon-theme "Paper"
gsettings set org.gnome.desktop.wm.preferences theme "Paper"
gsettings set org.gnome.desktop.interface cursor-theme "Paper"


