#!/bin/bash

sudo apt install python-pip python-dev tree
sudo pip install psutil thefuck

sudo apt install -y zsh
sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
